version: '3.3'

services:

  # ------------------------------------
  # App Container
  # ------------------------------------

  podio_api_delete:
    container_name: podio_api_delete
    deploy:
      resources:
        reservations:
          cpus: '0.5'
          memory: 1000M
        limits:
          cpus: '1'
          memory: 1000M
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    image: gbvsilva/podio-api-delete
    env_file:
      - "${PODIO_API_ENVFILE}"
      - "${DATABASE_ENVFILE}"
      - "${MISC_ENVFILE}"
